version: '3.5'

services:
  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=posteffectai
  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: always
    ports:
      - 3000:8080
  backend:
    build: ./backend
    depends_on:
      - postgresql
    restart: always
    ports:
      - 5000:4000
  